# must be unique in a given SonarQube instance
sonar.projectKey=ecom
sonar.projectName=ecom

sonar.projectVersion=1.0
sonar.language=java
sonar.sourceEncoding=UTF-8

sonar.sources=src/main/java
sonar.tests=src/test/java

# --- CODE COVERAGE EXCLUSIONS SECTION ---
# Excludes these packages specifically from Code Coverage reports
sonar.coverage.exclusions=**/model/**, **/util/**, **/utils/**, **/auth/**, **/entity/**, **/web/**, **/exceptions/**, **/repository/**, **/appconfigs/**, **/*Application.java

# --------------------------

sonar.cpd.exclusions=**/*Config.java
sonar.java.binaries=target/classes
sonar.dynamicAnalysis=reuseReports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.jacoco.reportPath=target/site/jacoco/jacoco.xml
sonar.java.coveragePlugin=jacoco
sonar.junit.reportsPath=target/surefire-reports
sonar.surefire.reportsPath=target/surefire-reports
sonar.verbose=true

sonar.scm.provider=git
sonar.projectBaseDir=

sonar.qualitygate.wait=true
